print ("Welcome to the mad lib generator.  Please follow along and type your input to each statement or question.")

print ("Name an object")
obj1 = input()
print ("Name the plural of your previous object")
obj3 = input()
print ("Name a different plural object")
obj2 = input()
print ("Name a color")
color1 = input()
print ("What is the weather today?")
weather = input()
print ("Name an adjective ending in 'ly'")
adj1 = input()
print ("Name a feeling (present tense)")
feeling = input()
print ("Name an adjective ending in 'ly'")
adj2 = input()
print ("Name a verb (past tense)")
verb1 = input()
print ("Name a color")
color2 = input()
print ("Name an adjective")
adj3 = input()
print ("Name a quality or a person or thing")
quality1 = input()
print ("Name a quality or a person or thing")
quality2 = input()

#Print Song Title
print ("\t*O Christmas Tree Mad Lib*")

#Verse 1
print ("\n O Christmas %s," %obj1 ) 
print ("O Christmas %s," %obj1 )
print ("How lovely are your %s!" %obj2)
print ("O Christmas %s," %obj1 )
print ("O Christmas %s," %obj1 )
print ("How lovely are your %s!" %obj2)
print ("Not only %s in summer's heat," %color1)
print ("But also winter's snow and %s" %weather)
print ("O Christmas %s," %obj1 )
print ("O Christmas %s," %obj1 )
print ("How lovely are your %s!" %obj2)

# Verse 2
print ("\n O Christmas %s," %obj1 ) 
print ("O Christmas %s," %obj1 )
print ("Of all the %s most %s;" %(obj3, adj1))
print ("O Christmas %s," %obj1 )
print ("O Christmas %s," %obj1 )
print ("Of all the %s most %s;" %(obj3, adj1))
print ("Each year you bring to us %s" %feeling)
print ("With %s shinning Christmas light!" %adj2)
print ("O Christmas %s," %obj1 )
print ("O Christmas %s," %obj1 )
print ("Of all the %s most %s." %(obj1, adj1))

# Verse 3
print ("\n O Christmas %s," %obj1 ) 
print ("O Christmas %s," %obj1 )
print ("We %s from all your beauty;" %verb1)
print ("O Christmas %s," %obj1 )
print ("O Christmas %s," %obj1 )
print ("We %s from all your beauty;" %verb1)
print ("Your bright %s leaves with %s cheer," %(color2, adj3))
print ("Give %s and %s throughout the year." %(quality1, quality2))
print ("O Christmas %s," %obj1 )
print ("O Christmas %s," %obj1 )
print ("We %s from all your beauty;" %verb1)


print ("\nHappy Holidays! And congratulations on making a new song: 'O Christmas %s!'" %obj1 )